apiVersion: v1
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiZmZjZjJkMjc4NWNlMTkyYzY0MjE3NTk0MGE5ZTU4MDkiLCJUdW5uZWxTZWNyZXQiOiJxbFc4TmxTdmc3Kzd1RHlodkN1VkU2V09JQWxMRm9uUU9oak9kRlZ3UEVrPSIsIlR1bm5lbElEIjoiYzM5NjQxNGEtZGEwNC00ODgwLTg1YzctZjIzOGUyZTE0MmQwIiwiRW5kcG9pbnQiOiIifQo=
kind: Secret
metadata:
  creationTimestamp: "2025-06-22T13:12:28Z"
  name: tunnel-credentials
  namespace: linkding
  resourceVersion: "966423"
  uid: 4766198c-5e8b-441f-b2cb-432f38776974
type: Opaque
