apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:v5sj/sOl0CEuQXrZ0BbOONFY93KBqD734RRhxlDDDAloPSbxmMSzVCbkFAC4Z/LICq3598o9zeQf4H4do9HEzSbERrTvyZZhve94QAU0+7pp/u0eHuJutBokuN09p7qnlYANO5HYHswg9/ndfASUyif38nA9eyNu5lO+s47pWEmew25lSCzMJdwZ6RRRO10Qhp+Q7rWt0nEHjxFXPGtAkT4kElcL8HTi/fZseJwffIOeRP2ol9iK/qpae1VnZ33Zpa84tOv4oEw32b+s+WZ6LRrWYWz99JReMC/tfsvI+UpuhbyZu0uBLPtkizE=,iv:kPWGFt3ifJy6x2zVCcDzbuxPrAgE1JqlYD7tp+NpueQ=,tag:CQYgPiCKQV56uZJtjHExxg==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2025-06-22T13:29:48Z"
    name: tunnel-credentials
    namespace: linkding
    resourceVersion: "967934"
    uid: cab8ceb9-526e-4607-8227-5c39e205625b
type: Opaque
sops:
    age:
        - recipient: age1w3a9lw35hqjju7sxsxhrxr83vde2s3zwgtqy3am2t2tr9gr245cs4fm8py
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlek5vVVRVZDcwTjlIMDVp
            djk5b1ZFek95bXBnUkY1SE00SkFkVWFjTXhBCnVBOW16NnZKZHptbVZYTFZzRzQz
            S3Y2TUhRUzBmQ09ISVphZWJvQ29WbHMKLS0tIDE4cXFrbU9rQmdraldEWDh0Sjdz
            dy9KWFUycWhocE85dGFOWVVQaTZyb1UKcbRefKpMlEnq7XXfGYVnU3LD/Lw0Bpbj
            HoMdBaNHXj46MBAAcXfjxIYNS20l349593gdkz5nQgkgzgLuhqX4ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T13:31:47Z"
    mac: ENC[AES256_GCM,data:az2p/y8SIetu6EUa/gCTp2w0h8Vgx2ytdc3hO4PIYfJXbTyZ00GwKVV6ubOoKlHFY73LZ1ZCye+txzURoYBMQB8hTTgI7a6eiz5rQ+U8wOj3I2FFkp448rjTQDQVCyl8q5Fx5j/XbZlXXn0wPqfQcjp9sQfcSGBIjplPW4uaDak=,iv:pKKweHSEFzzNpr3NPMrjQ7DKBDpJe/vcY7slle8uTG8=,tag:AKY7JSUeBRVdNdeorJKQuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
