apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:1HTuWQ==,iv:HnN58Z77Ou9CE6n3laVOP5vo62RJvllLLb8wA1eSyNM=,tag:N7KIH78TIZEWYTUcINRh+g==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:5nGSrwQS4tnntnjA,iv:AXsFd7FXiZzltUy/ySDHJ5vf6qn2vEet/yopNwrM01o=,tag:7mnzDsQceRE3QIvAH2e46g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1w3a9lw35hqjju7sxsxhrxr83vde2s3zwgtqy3am2t2tr9gr245cs4fm8py
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXV0cydERSR2haV0t5elJD
            THIwOU03TnF4aWtXZ1NNT0hWOG9PN25iTVNBCjBYWUxsOFNIVTNwNGI2a09hYkkw
            RGtuaStHYWUrZ3RTVVZMTFNlcWUvd1UKLS0tIDNzRUFzSFB0VE55dnFXQUlyd283
            VW51djUya3hUelZwMDdKV09ac1FOWjgKNa1TqLHPibdJzasDpmdRUQG8vbsLsFGz
            2Ck30hJC4IML/UHFa3b048DcvTJ3ecI87s7aFmQTSV0tpEbqVyDvVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T15:10:00Z"
    mac: ENC[AES256_GCM,data:p/Fw1Uzxst78TloBubhapCXPkrMWJDOhndqOdA5xghb2QY3l8Zjfz+hgWFH5UYtODtMPHpHnujQqZX8yIS9EvsJq6s/RAfvXRL5Hc91bh+tn4hzKSM7FELSPzOU2RuzaHVc1kK5NQ3IppHuX1Pv6qLETqMR0eLYCdFnBYLxgLKw=,iv:tDC6sDWD+x7fE0UPgjPGfIfmZjiR+rIPubI5pSYod40=,tag:qY0zoYKnGw2x/rAm2wtM3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
